### ISSUE TITLE
Cleaning up the code for our first working model.

### ISSUE THREAD

**Issue by perjah20** [perjah20/AOOP-Project#1]
### Overview
We almost have a working project. What is left are minor improvements and fixes. 

### Todo before working version:

- [ ] Optimize the way the grid is updated in SokobanGameGUI
#https://github.com/perjah20/AOOP-Project/blob/b558ba063db89e1986ec7df579e30acd040bcacf/src/main/java/sokoban/SokobanGameGUI.java#L28-L42

- [x] Implement resetLevel
 # https://github.com/perjah20/AOOP-Project/blob/b558ba063db89e1986ec7df579e30acd040bcacf/src/main/java/sokoban/SokobanGameModel.java#L132-L134
- [x] Implement saveGame function (Not urgent)
 # https://github.com/perjah20/AOOP-Project/blob/b558ba063db89e1986ec7df579e30acd040bcacf/src/main/java/sokoban/SokobanGameModel.java#L136-L138
- [x] Implement loadGame function (Not urgent)
# https://github.com/perjah20/AOOP-Project/blob/b558ba063db89e1986ec7df579e30acd040bcacf/src/main/java/sokoban/SokobanGameModel.java#L140-L142

- [x] Remove constructor from SokobanGameModel and SokobanGameGUI. Since we can update the size of gameGrid under runtime, the classes observing should automatically handle the resizing
# https://github.com/perjah20/AOOP-Project/blob/b558ba063db89e1986ec7df579e30acd040bcacf/src/main/java/sokoban/SokobanGame.java#L11-L12
Means we have to rethink the constructor in TileGameGUI.
# https://github.com/perjah20/AOOP-Project/blob/b558ba063db89e1986ec7df579e30acd040bcacf/src/main/java/tileGame/TileGameGUI.java#L19-L29
And TileGameModel
# https://github.com/perjah20/AOOP-Project/blob/b558ba063db89e1986ec7df579e30acd040bcacf/src/main/java/tileGame/TileGameModel.java#L15-L19

- [x] Remove convert to private and add methods to access them instead. 
# https://github.com/perjah20/AOOP-Project/blob/b558ba063db89e1986ec7df579e30acd040bcacf/src/main/java/tileGame/TileGameGUI.java#L153-L154
